import { Property, PropertyType, PropertyGroup } from "@/gameInterfaces/property";

export const PROPERTY_GROUPS: Record<string, PropertyGroup> = {
    "egypt": { name: "Egypt", color: "#8B4513", properties: ["mediterranean_avenue", "baltic_avenue"] },
    "iceland": { name: "Iceland", color: "#87CEEB", properties: ["oriental_avenue", "vermont_avenue", "connecticut_avenue"] },
    "japan": { name: "Japan", color: "#FF69B4", properties: ["st_charles_place", "states_avenue", "virginia_avenue"] },
    "netherlands": { name: "Netherlands", color: "#FFA500", properties: ["st_james_place", "tennessee_avenue", "new_york_avenue"] },
    "canada": { name: "Canada", color: "#FF0000", properties: ["kentucky_avenue", "indiana_avenue", "illinois_avenue"] },
    "brazil": { name: "Brazil", color: "#FFFF00", properties: ["atlantic_avenue", "ventnor_avenue", "marvin_gardens"] },
    "ireland": { name: "Ireland", color: "#008000", properties: ["pacific_avenue", "north_carolina_avenue", "pennsylvania_avenue"] },
    "usa": { name: "USA", color: "#00008B", properties: ["park_place", "boardwalk"] },
    "railroad": { name: "Railroad", color: "#000000", properties: ["reading_railroad", "pennsylvania_railroad"] },
    "airplane": { name: "Airplane", color: "#808080", properties: ["heathrow_airport", "jfk_airport"] },
    "electric": { name: "Electric", color: "#FFFFE0", properties: ["electric_company"] },
    "water": { name: "Water", color: "#00FFFF", properties: ["water_works"] },
};

export const PROPERTIES: Record<string, Property> = {
    "go": { name: "GO", type: PropertyType.GO, position: 0 },
    "mediterranean_avenue": { name: "Mediterranean Avenue", type: PropertyType.STREET, position: 1, price: 60, rent: [2, 10, 30, 90, 160, 250], housePrice: 50, houses: 0, mortgageValue: 30, owner: null, isMortgaged: false, groupId: "egypt" },
    "community_chest_1": { name: "Community Chest", type: PropertyType.CHEST, position: 2 },
    "baltic_avenue": { name: "Baltic Avenue", type: PropertyType.STREET, position: 3, price: 60, rent: [4, 20, 60, 180, 320, 450], housePrice: 50, houses: 0, mortgageValue: 30, owner: null, isMortgaged: false, groupId: "egypt" },
    "income_tax": { name: "Income Tax", type: PropertyType.TAX, position: 4, amount: 200 },
    "reading_railroad": { name: "Reading Railroad", type: PropertyType.TRANSPORT, position: 5, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "railroad" },
    "oriental_avenue": { name: "Oriental Avenue", type: PropertyType.STREET, position: 6, price: 100, rent: [6, 30, 90, 270, 400, 550], housePrice: 50, houses: 0, mortgageValue: 50, owner: null, isMortgaged: false, groupId: "iceland" },
    "chance_1": { name: "Chance", type: PropertyType.CHANCE, position: 7 },
    "vermont_avenue": { name: "Vermont Avenue", type: PropertyType.STREET, position: 8, price: 100, rent: [6, 30, 90, 270, 400, 550], housePrice: 50, houses: 0, mortgageValue: 50, owner: null, isMortgaged: false, groupId: "iceland" },
    "connecticut_avenue": { name: "Connecticut Avenue", type: PropertyType.STREET, position: 9, price: 120, rent: [8, 40, 100, 300, 450, 600], housePrice: 50, houses: 0, mortgageValue: 60, owner: null, isMortgaged: false, groupId: "iceland" },
    "jail": { name: "Jail", type: PropertyType.JAIL, position: 10 },
    "st_charles_place": { name: "St. Charles Place", type: PropertyType.STREET, position: 11, price: 140, rent: [10, 50, 150, 450, 625, 750], housePrice: 100, houses: 0, mortgageValue: 70, owner: null, isMortgaged: false, groupId: "japan" },
    "electric_company": { name: "Electric Company", type: PropertyType.UTILITY, position: 12, price: 150, multipliers: [4, 10], mortgageValue: 75, owner: null, isMortgaged: false, groupId: "electric" },
    "states_avenue": { name: "States Avenue", type: PropertyType.STREET, position: 13, price: 140, rent: [10, 50, 150, 450, 625, 750], housePrice: 100, houses: 0, mortgageValue: 70, owner: null, isMortgaged: false, groupId: "japan" },
    "virginia_avenue": { name: "Virginia Avenue", type: PropertyType.STREET, position: 14, price: 160, rent: [12, 60, 180, 500, 700, 900], housePrice: 100, houses: 0, mortgageValue: 80, owner: null, isMortgaged: false, groupId: "japan" },
    "pennsylvania_railroad": { name: "Pennsylvania Railroad", type: PropertyType.TRANSPORT, position: 15, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "railroad" },
    "st_james_place": { name: "St. James Place", type: PropertyType.STREET, position: 16, price: 180, rent: [14, 70, 200, 550, 750, 950], housePrice: 100, houses: 0, mortgageValue: 90, owner: null, isMortgaged: false, groupId: "netherlands" },
    "community_chest_2": { name: "Community Chest", type: PropertyType.CHEST, position: 17 },
    "tennessee_avenue": { name: "Tennessee Avenue", type: PropertyType.STREET, position: 18, price: 180, rent: [14, 70, 200, 550, 750, 950], housePrice: 100, houses: 0, mortgageValue: 90, owner: null, isMortgaged: false, groupId: "netherlands" },
    "new_york_avenue": { name: "New York Avenue", type: PropertyType.STREET, position: 19, price: 200, rent: [16, 80, 220, 600, 800, 1000], housePrice: 100, houses: 0, mortgageValue: 100, owner: null, isMortgaged: false, groupId: "netherlands" },
    "vacation": { name: "Vacation", type: PropertyType.VACATION, position: 20 },
    "kentucky_avenue": { name: "Kentucky Avenue", type: PropertyType.STREET, position: 21, price: 220, rent: [18, 90, 250, 700, 875, 1050], housePrice: 150, houses: 0, mortgageValue: 110, owner: null, isMortgaged: false, groupId: "canada" },
    "chance_2": { name: "Chance", type: PropertyType.CHANCE, position: 22 },
    "indiana_avenue": { name: "Indiana Avenue", type: PropertyType.STREET, position: 23, price: 220, rent: [18, 90, 250, 700, 875, 1050], housePrice: 150, houses: 0, mortgageValue: 110, owner: null, isMortgaged: false, groupId: "canada" },
    "illinois_avenue": { name: "Illinois Avenue", type: PropertyType.STREET, position: 24, price: 240, rent: [20, 100, 300, 750, 925, 1100], housePrice: 150, houses: 0, mortgageValue: 120, owner: null, isMortgaged: false, groupId: "canada" },
    "heathrow_airport": { name: "Heathrow Airport", type: PropertyType.TRANSPORT, position: 25, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "airplane" },
    "atlantic_avenue": { name: "Atlantic Avenue", type: PropertyType.STREET, position: 26, price: 260, rent: [22, 110, 330, 800, 975, 1150], housePrice: 150, houses: 0, mortgageValue: 130, owner: null, isMortgaged: false, groupId: "brazil" },
    "ventnor_avenue": { name: "Ventnor Avenue", type: PropertyType.STREET, position: 27, price: 260, rent: [22, 110, 330, 800, 975, 1150], housePrice: 150, houses: 0, mortgageValue: 130, owner: null, isMortgaged: false, groupId: "brazil" },
    "water_works": { name: "Water Works", type: PropertyType.UTILITY, position: 28, price: 150, multipliers: [4, 10], mortgageValue: 75, owner: null, isMortgaged: false, groupId: "water" },
    "marvin_gardens": { name: "Marvin Gardens", type: PropertyType.STREET, position: 29, price: 280, rent: [24, 120, 360, 850, 1025, 1200], housePrice: 150, houses: 0, mortgageValue: 140, owner: null, isMortgaged: false, groupId: "brazil" },
    "go_to_jail": { name: "Go to Jail", type: PropertyType.CHANCE, position: 30 },
    "pacific_avenue": { name: "Pacific Avenue", type: PropertyType.STREET, position: 31, price: 300, rent: [26, 130, 390, 900, 1100, 1275], housePrice: 200, houses: 0, mortgageValue: 150, owner: null, isMortgaged: false, groupId: "ireland" },
    "north_carolina_avenue": { name: "North Carolina Avenue", type: PropertyType.STREET, position: 32, price: 300, rent: [26, 130, 390, 900, 1100, 1275], housePrice: 200, houses: 0, mortgageValue: 150, owner: null, isMortgaged: false, groupId: "ireland" },
    "community_chest_3": { name: "Community Chest", type: PropertyType.CHEST, position: 33 },
    "pennsylvania_avenue": { name: "Pennsylvania Avenue", type: PropertyType.STREET, position: 34, price: 320, rent: [28, 150, 450, 1000, 1200, 1400], housePrice: 200, houses: 0, mortgageValue: 160, owner: null, isMortgaged: false, groupId: "ireland" },
    "jfk_airport": { name: "JFK Airport", type: PropertyType.TRANSPORT, position: 35, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "airplane" },
    "chance_3": { name: "Chance", type: PropertyType.CHANCE, position: 36 },
    "park_place": { name: "Park Place", type: PropertyType.STREET, position: 37, price: 350, rent: [35, 175, 500, 1100, 1300, 1500], housePrice: 200, houses: 0, mortgageValue: 175, owner: null, isMortgaged: false, groupId: "usa" },
    "luxury_tax": { name: "Luxury Tax", type: PropertyType.TAX, position: 38, amount: 100 },
    "boardwalk": { name: "Boardwalk", type: PropertyType.STREET, position: 39, price: 400, rent: [50, 200, 600, 1400, 1700, 2000], housePrice: 200, houses: 0, mortgageValue: 200, owner: null, isMortgaged: false, groupId: "usa" }
};
