import { Property, PropertyType, PropertyGroup } from "@/gameInterfaces/property";

export const PROPERTY_GROUPS: Record<string, PropertyGroup> = {
    egypt: { name: "Egypt", image: "/images/groups/egypt.png", properties: ["cairo", "alexandria"] },
    iceland: { name: "Iceland", image: "/images/groups/iceland.png", properties: ["reykjavik", "akureyri", "keflavik"] },
    japan: { name: "Japan", image: "/images/groups/japan.png", properties: ["tokyo", "osaka", "kyoto"] },
    netherlands: { name: "Netherlands", image: "/images/groups/netherlands.png", properties: ["amsterdam", "rotterdam", "utrecht"] },
    canada: { name: "Canada", image: "/images/groups/canada.png", properties: ["toronto", "vancouver", "montreal"] },
    brazil: { name: "Brazil", image: "/images/groups/brazil.png", properties: ["rio", "sao", "brasilia"] },
    ireland: { name: "Ireland", image: "/images/groups/ireland.png", properties: ["dublin", "cork", "galway"] },
    usa: { name: "USA", image: "/images/groups/usa.png", properties: ["newyork", "losangeles", "seattle"] },
    airports: { name: "Airports", image: "/images/groups/railroad.png", properties: ["heathrow", "jfk", "changi", "haneda"] },
    electric: { name: "Electric", image: "/images/groups/electric.png", properties: ["solar", "wind"] },
    water: { name: "Water", image: "/images/groups/water.png", properties: ["nile", "amazon"] },
};

export const PROPERTIES: Record<string, Property> = {
    go: { name: "GO", type: PropertyType.GO, position: 0 },
    cairo: { name: "Cairo", type: PropertyType.STREET, position: 1, price: 60, rent: [2, 10, 30, 90, 160, 250], housePrice: 50, houses: 0, mortgageValue: 30, owner: null, isMortgaged: false, groupId: "egypt" },
    chest: { name: "Chest", type: PropertyType.CHEST, position: 2 },
    alexandria: { name: "Alexandria", type: PropertyType.STREET, position: 3, price: 60, rent: [4, 20, 60, 180, 320, 450], housePrice: 50, houses: 0, mortgageValue: 30, owner: null, isMortgaged: false, groupId: "egypt" },
    tax: { name: "Tax", type: PropertyType.TAX, position: 4, percentage: 0.1 },
    heathrow: { name: "Heathrow", type: PropertyType.TRANSPORT, position: 5, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "airports" },
    reykjavik: { name: "Reykjavik", type: PropertyType.STREET, position: 6, price: 100, rent: [6, 30, 90, 270, 400, 550], housePrice: 50, houses: 0, mortgageValue: 50, owner: null, isMortgaged: false, groupId: "iceland" },
    solar: { name: "Solar", type: PropertyType.UTILITY, position: 7, price: 150, multipliers: [4, 10], mortgageValue: 75, owner: null, isMortgaged: false, groupId: "electric" },
    akureyri: { name: "Akureyri", type: PropertyType.STREET, position: 8, price: 100, rent: [6, 30, 90, 270, 400, 550], housePrice: 50, houses: 0, mortgageValue: 50, owner: null, isMortgaged: false, groupId: "iceland" },
    keflavik: { name: "Keflavik", type: PropertyType.STREET, position: 9, price: 120, rent: [8, 40, 100, 300, 450, 600], housePrice: 50, houses: 0, mortgageValue: 60, owner: null, isMortgaged: false, groupId: "iceland" },
    jail: { name: "Jail", type: PropertyType.JAIL, position: 10 },
    tokyo: { name: "Tokyo", type: PropertyType.STREET, position: 11, price: 140, rent: [10, 50, 150, 450, 625, 750], housePrice: 100, houses: 0, mortgageValue: 70, owner: null, isMortgaged: false, groupId: "japan" },
    nile: { name: "Nile", type: PropertyType.UTILITY, position: 12, price: 150, multipliers: [4, 10], mortgageValue: 75, owner: null, isMortgaged: false, groupId: "water" },
    osaka: { name: "Osaka", type: PropertyType.STREET, position: 13, price: 140, rent: [10, 50, 150, 450, 625, 750], housePrice: 100, houses: 0, mortgageValue: 70, owner: null, isMortgaged: false, groupId: "japan" },
    kyoto: { name: "Kyoto", type: PropertyType.STREET, position: 14, price: 160, rent: [12, 60, 180, 500, 700, 900], housePrice: 100, houses: 0, mortgageValue: 80, owner: null, isMortgaged: false, groupId: "japan" },
    jfk: { name: "JFK", type: PropertyType.TRANSPORT, position: 15, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "airports" },
    amsterdam: { name: "Amsterdam", type: PropertyType.STREET, position: 16, price: 180, rent: [14, 70, 200, 550, 750, 950], housePrice: 100, houses: 0, mortgageValue: 90, owner: null, isMortgaged: false, groupId: "netherlands" },
    surprise: { name: "Surprise", type: PropertyType.SURPRISE, position: 17 },
    rotterdam: { name: "Rotterdam", type: PropertyType.STREET, position: 18, price: 180, rent: [14, 70, 200, 550, 750, 950], housePrice: 100, houses: 0, mortgageValue: 90, owner: null, isMortgaged: false, groupId: "netherlands" },
    utrecht: { name: "Utrecht", type: PropertyType.STREET, position: 19, price: 200, rent: [16, 80, 220, 600, 800, 1000], housePrice: 100, houses: 0, mortgageValue: 100, owner: null, isMortgaged: false, groupId: "netherlands" },
    vacation: { name: "Vacation", type: PropertyType.VACATION, position: 20 },
    toronto: { name: "Toronto", type: PropertyType.STREET, position: 21, price: 220, rent: [18, 90, 250, 700, 875, 1050], housePrice: 150, houses: 0, mortgageValue: 110, owner: null, isMortgaged: false, groupId: "canada" },
    wind: { name: "Wind", type: PropertyType.UTILITY, position: 22, price: 150, multipliers: [4, 10], mortgageValue: 75, owner: null, isMortgaged: false, groupId: "electric" },
    vancouver: { name: "Vancouver", type: PropertyType.STREET, position: 23, price: 220, rent: [18, 90, 250, 700, 875, 1050], housePrice: 150, houses: 0, mortgageValue: 110, owner: null, isMortgaged: false, groupId: "canada" },
    montreal: { name: "Montreal", type: PropertyType.STREET, position: 24, price: 240, rent: [20, 100, 300, 750, 925, 1100], housePrice: 150, houses: 0, mortgageValue: 120, owner: null, isMortgaged: false, groupId: "canada" },
    changi: { name: "Changi", type: PropertyType.TRANSPORT, position: 25, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "airports" },
    rio: { name: "Rio", type: PropertyType.STREET, position: 26, price: 260, rent: [22, 110, 330, 800, 975, 1150], housePrice: 150, houses: 0, mortgageValue: 130, owner: null, isMortgaged: false, groupId: "brazil" },
    sao: { name: "Sao", type: PropertyType.STREET, position: 27, price: 260, rent: [22, 110, 330, 800, 975, 1150], housePrice: 150, houses: 0, mortgageValue: 130, owner: null, isMortgaged: false, groupId: "brazil" },
    amazon: { name: "Amazon", type: PropertyType.UTILITY, position: 28, price: 150, multipliers: [4, 10], mortgageValue: 75, owner: null, isMortgaged: false, groupId: "water" },
    brasilia: { name: "Brasilia", type: PropertyType.STREET, position: 29, price: 280, rent: [24, 120, 360, 850, 1025, 1200], housePrice: 150, houses: 0, mortgageValue: 140, owner: null, isMortgaged: false, groupId: "brazil" },
    gotojail: { name: "GoToJail", type: PropertyType.CHANCE, position: 30 },
    dublin: { name: "Dublin", type: PropertyType.STREET, position: 31, price: 300, rent: [26, 130, 390, 900, 1100, 1275], housePrice: 200, houses: 0, mortgageValue: 150, owner: null, isMortgaged: false, groupId: "ireland" },
    cork: { name: "Cork", type: PropertyType.STREET, position: 32, price: 300, rent: [26, 130, 390, 900, 1100, 1275], housePrice: 200, houses: 0, mortgageValue: 150, owner: null, isMortgaged: false, groupId: "ireland" },
    chance: { name: "Chance", type: PropertyType.CHANCE, position: 33 },
    galway: { name: "Galway", type: PropertyType.STREET, position: 34, price: 320, rent: [28, 150, 450, 1000, 1200, 1400], housePrice: 200, houses: 0, mortgageValue: 160, owner: null, isMortgaged: false, groupId: "ireland" },
    haneda: { name: "Haneda", type: PropertyType.TRANSPORT, position: 35, price: 200, rent: [50, 100], mortgageValue: 100, owner: null, isMortgaged: false, groupId: "airports" },
    newyork: { name: "NewYork", type: PropertyType.STREET, position: 36, price: 350, rent: [35, 175, 500, 1100, 1300, 1500], housePrice: 200, houses: 0, mortgageValue: 175, owner: null, isMortgaged: false, groupId: "usa" },
    luxury: { name: "Luxury", type: PropertyType.TAX, position: 37, amount: 100 },
    losangeles: { name: "LosAngeles", type: PropertyType.STREET, position: 38, price: 400, rent: [50, 200, 600, 1400, 1700, 2000], housePrice: 200, houses: 0, mortgageValue: 200, owner: null, isMortgaged: false, groupId: "usa" },
    seattle: { name: "Seattle", type: PropertyType.STREET, position: 39, price: 400, rent: [50, 200, 600, 1400, 1700, 2000], housePrice: 200, houses: 0, mortgageValue: 200, owner: null, isMortgaged: false, groupId: "usa" }
};
