export enum TurnPhase {
    WAITING_FOR_PLAYERS = "WAITING_FOR_PLAYERS",
    STARTING_GAME = "STARTING_GAME",
    PRE_ROLL = "PRE_ROLL",
    ROLLING = "ROLLING",
    POST_ROLL = "POST_ROLL",
    AUCTION = "AUCTION",
    GAME_OVER = "GAME_OVER"
}